
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'statementADD FLOAT IDENTIFIER IF INTEGER LPAREN QUOTE RPAREN STRING STRING_END STRING_START SUBempty :statement : emptystatement : sexprsexpr : seqsexpr : LPAREN IDENTIFIER sexpr RPARENsexpr : LPAREN ADD sexpr RPARENsexpr : LPAREN SUB sexpr RPARENseq : atomseq : atom seqatom : INTEGERatom : FLOATatom : STRINGatom : IDENTIFIER'
    
_lr_action_items = {'$end':([0,1,2,3,4,6,7,8,9,10,14,18,19,20,],[-1,0,-2,-3,-4,-13,-8,-10,-11,-12,-9,-5,-6,-7,]),'LPAREN':([0,11,12,13,],[5,5,5,5,]),'INTEGER':([0,6,7,8,9,10,11,12,13,],[8,-13,8,-10,-11,-12,8,8,8,]),'FLOAT':([0,6,7,8,9,10,11,12,13,],[9,-13,9,-10,-11,-12,9,9,9,]),'STRING':([0,6,7,8,9,10,11,12,13,],[10,-13,10,-10,-11,-12,10,10,10,]),'IDENTIFIER':([0,5,6,7,8,9,10,11,12,13,],[6,11,-13,6,-10,-11,-12,6,6,6,]),'RPAREN':([4,6,7,8,9,10,14,15,16,17,18,19,20,],[-4,-13,-8,-10,-11,-12,-9,18,19,20,-5,-6,-7,]),'ADD':([5,],[12,]),'SUB':([5,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'empty':([0,],[2,]),'sexpr':([0,11,12,13,],[3,15,16,17,]),'seq':([0,7,11,12,13,],[4,14,4,4,4,]),'atom':([0,7,11,12,13,],[7,7,7,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',9),
  ('statement -> empty','statement',1,'p_statement_empty','parser.py',13),
  ('statement -> sexpr','statement',1,'p_statement_sexpr','parser.py',17),
  ('sexpr -> seq','sexpr',1,'p_sexpr_seq','parser.py',23),
  ('sexpr -> LPAREN IDENTIFIER sexpr RPAREN','sexpr',4,'p_sexpr_function','parser.py',29),
  ('sexpr -> LPAREN ADD sexpr RPAREN','sexpr',4,'p_sexpr_addition','parser.py',33),
  ('sexpr -> LPAREN SUB sexpr RPAREN','sexpr',4,'p_sexpr_subtraction','parser.py',45),
  ('seq -> atom','seq',1,'p_seq','parser.py',52),
  ('seq -> atom seq','seq',2,'p_seq_recursive','parser.py',57),
  ('atom -> INTEGER','atom',1,'p_atom_integer','parser.py',65),
  ('atom -> FLOAT','atom',1,'p_atom_float','parser.py',72),
  ('atom -> STRING','atom',1,'p_atom_STRING','parser.py',81),
  ('atom -> IDENTIFIER','atom',1,'p_atom_identifier','parser.py',88),
]
